version: 0.2

phases:
  pre_build:
    commands:
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 248133746893.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t coworking:$CODEBUILD_BUILD_NUMBER .
      - docker tag coworking:$CODEBUILD_BUILD_NUMBER 248133746893.dkr.ecr.us-east-1.amazonaws.com/coworking:$CODEBUILD_BUILD_NUMBER
  post_build:
    commands:
      - docker push 248133746893.dkr.ecr.us-east-1.amazonaws.com/coworking:$CODEBUILD_BUILD_NUMBER
